/**
 * PDF Generator Module
 * Uses html2pdf.js to generate client summary PDFs
 */

import html2pdf from 'html2pdf.js';

export interface ClientPDFData {
  id: string;
  name: string;
  email: string;
  phone: string;
  age: number;
  income: number;
  risk_profile: string;
  portfolio_value: number;
  total_investments: number;
  conversion_probability: number;
  interests: string[];
  last_contact: string;
  daysSinceContact: number;
  lifecycle_stage: string;
  activities: {
    type: string;
    date: string;
    outcome: string;
    notes: string;
  }[];
  portfolio: {
    investment_name: string;
    investment_type: string;
    amount_invested: number;
    current_value: number;
    performance: number;
  }[];
}

export interface AdvisorInfo {
  name: string;
  email: string;
  phone: string;
  company: string;
}

export interface PredictionData {
  investment_name: string;
  confidence: number;
  reason: string;
}

const defaultAdvisor: AdvisorInfo = {
  name: 'James Wilson',
  email: 'james.wilson@alphaforce.com',
  phone: '(555) 123-4567',
  company: 'AlphaForce Wealth Management',
};

function formatCurrency(value: number): string {
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
    maximumFractionDigits: 0,
  }).format(value);
}

function formatDate(date: Date): string {
  return date.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
}

function generateTalkingPoints(client: ClientPDFData): string[] {
  const points: string[] = [];

  if (client.daysSinceContact > 7) {
    points.push(`Follow up on previous conversation from ${client.last_contact}`);
  }

  if (client.interests.includes('technology')) {
    points.push('Discuss recent tech sector performance and growth opportunities');
  }

  if (client.risk_profile === 'high') {
    points.push('Review high-growth investment options matching risk appetite');
  } else if (client.risk_profile === 'low') {
    points.push('Focus on stable, fixed-income options for capital preservation');
  }

  if (client.portfolio.length > 0) {
    const topPerformer = client.portfolio.reduce((a, b) =>
      a.performance > b.performance ? a : b
    );
    if (topPerformer.performance > 0) {
      points.push(
        `Highlight strong performance of ${topPerformer.investment_name} (+${topPerformer.performance}%)`
      );
    }
  }

  if (client.conversion_probability > 70) {
    points.push('Present specific investment proposal - high conversion likelihood');
  }

  if (client.interests.includes('dividends') || client.interests.includes('income')) {
    points.push('Discuss dividend-paying investments for regular income');
  }

  return points.length > 0
    ? points.slice(0, 4)
    : [
        'Schedule introductory portfolio review',
        'Discuss investment goals and timeline',
        'Assess risk tolerance and preferences',
      ];
}

export function generatePDFContent(
  client: ClientPDFData,
  predictions: PredictionData[] = [],
  advisor: AdvisorInfo = defaultAdvisor
): string {
  const talkingPoints = generateTalkingPoints(client);
  const topPrediction = predictions[0];
  const recentActivities = client.activities.slice(0, 5);

  return `
    <div id="pdf-content" style="font-family: 'Helvetica Neue', Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 40px; color: #1a1a1a;">
      <!-- Header -->
      <div style="border-bottom: 3px solid #000; padding-bottom: 20px; margin-bottom: 30px;">
        <div style="display: flex; justify-content: space-between; align-items: flex-start;">
          <div>
            <h1 style="margin: 0; font-size: 32px; font-weight: 700; color: #000;">Client Summary</h1>
            <p style="margin: 5px 0 0 0; font-size: 14px; color: #666;">Generated by AlphaForce</p>
          </div>
          <div style="text-align: right;">
            <p style="margin: 0; font-size: 14px; color: #666;">${formatDate(new Date())}</p>
          </div>
        </div>
      </div>

      <!-- Client Info Section -->
      <div style="background: #f8f8f8; border-radius: 8px; padding: 24px; margin-bottom: 30px;">
        <div style="display: flex; justify-content: space-between;">
          <div>
            <h2 style="margin: 0 0 8px 0; font-size: 24px; font-weight: 600;">${client.name}</h2>
            <p style="margin: 0; font-size: 14px; color: #666;">
              <span style="display: inline-block; margin-right: 20px;">📧 ${client.email}</span>
              <span style="display: inline-block;">📞 ${client.phone}</span>
            </p>
          </div>
          <div style="text-align: right;">
            <span style="display: inline-block; padding: 6px 16px; background: ${
              client.risk_profile === 'high' ? '#000' : client.risk_profile === 'medium' ? '#666' : '#999'
            }; color: white; border-radius: 20px; font-size: 12px; font-weight: 600; text-transform: uppercase;">
              ${client.risk_profile} Risk
            </span>
          </div>
        </div>
      </div>

      <!-- Key Metrics -->
      <div style="margin-bottom: 30px;">
        <h3 style="font-size: 18px; font-weight: 600; margin: 0 0 16px 0; color: #000;">Key Metrics</h3>
        <div style="display: flex; gap: 16px;">
          <div style="flex: 1; background: #fff; border: 1px solid #e0e0e0; border-radius: 8px; padding: 16px; text-align: center;">
            <p style="margin: 0; font-size: 24px; font-weight: 700; color: #000;">${formatCurrency(client.portfolio_value)}</p>
            <p style="margin: 4px 0 0 0; font-size: 12px; color: #666;">Portfolio Value</p>
          </div>
          <div style="flex: 1; background: #fff; border: 1px solid #e0e0e0; border-radius: 8px; padding: 16px; text-align: center;">
            <p style="margin: 0; font-size: 24px; font-weight: 700; color: #000;">${client.total_investments}</p>
            <p style="margin: 4px 0 0 0; font-size: 12px; color: #666;">Total Investments</p>
          </div>
          <div style="flex: 1; background: #fff; border: 1px solid #e0e0e0; border-radius: 8px; padding: 16px; text-align: center;">
            <p style="margin: 0; font-size: 24px; font-weight: 700; color: ${
              client.daysSinceContact > 14 ? '#dc2626' : client.daysSinceContact > 7 ? '#ca8a04' : '#16a34a'
            };">${client.daysSinceContact} days</p>
            <p style="margin: 4px 0 0 0; font-size: 12px; color: #666;">Since Last Contact</p>
          </div>
          <div style="flex: 1; background: #fff; border: 1px solid #e0e0e0; border-radius: 8px; padding: 16px; text-align: center;">
            <p style="margin: 0; font-size: 24px; font-weight: 700; color: ${
              client.conversion_probability > 70 ? '#16a34a' : client.conversion_probability > 50 ? '#ca8a04' : '#666'
            };">${client.conversion_probability}%</p>
            <p style="margin: 4px 0 0 0; font-size: 12px; color: #666;">Conversion Probability</p>
          </div>
        </div>
      </div>

      <!-- Talking Points -->
      <div style="margin-bottom: 30px;">
        <h3 style="font-size: 18px; font-weight: 600; margin: 0 0 16px 0; color: #000;">📝 Talking Points</h3>
        <div style="background: #fafafa; border-left: 4px solid #000; padding: 16px 20px;">
          <ol style="margin: 0; padding-left: 20px;">
            ${talkingPoints.map((point) => `<li style="margin-bottom: 8px; font-size: 14px; line-height: 1.5;">${point}</li>`).join('')}
          </ol>
        </div>
      </div>

      ${
        topPrediction
          ? `
      <!-- ML Recommendation -->
      <div style="margin-bottom: 30px;">
        <h3 style="font-size: 18px; font-weight: 600; margin: 0 0 16px 0; color: #000;">🎯 Top Investment Recommendation</h3>
        <div style="background: #f0f9ff; border: 1px solid #0ea5e9; border-radius: 8px; padding: 20px;">
          <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 12px;">
            <span style="font-size: 18px; font-weight: 600;">${topPrediction.investment_name}</span>
            <span style="background: ${topPrediction.confidence > 70 ? '#16a34a' : topPrediction.confidence > 50 ? '#ca8a04' : '#666'}; color: white; padding: 4px 12px; border-radius: 20px; font-size: 12px; font-weight: 600;">
              ${topPrediction.confidence}% Confidence
            </span>
          </div>
          <p style="margin: 0; font-size: 14px; color: #555;">${topPrediction.reason}</p>
        </div>
      </div>
      `
          : ''
      }

      <!-- Recent Activities -->
      ${
        recentActivities.length > 0
          ? `
      <div style="margin-bottom: 30px;">
        <h3 style="font-size: 18px; font-weight: 600; margin: 0 0 16px 0; color: #000;">📅 Recent Activities</h3>
        <table style="width: 100%; border-collapse: collapse; font-size: 13px;">
          <thead>
            <tr style="background: #f5f5f5;">
              <th style="padding: 12px; text-align: left; border-bottom: 2px solid #ddd; font-weight: 600;">Date</th>
              <th style="padding: 12px; text-align: left; border-bottom: 2px solid #ddd; font-weight: 600;">Type</th>
              <th style="padding: 12px; text-align: left; border-bottom: 2px solid #ddd; font-weight: 600;">Outcome</th>
              <th style="padding: 12px; text-align: left; border-bottom: 2px solid #ddd; font-weight: 600;">Notes</th>
            </tr>
          </thead>
          <tbody>
            ${recentActivities
              .map(
                (activity) => `
              <tr>
                <td style="padding: 10px 12px; border-bottom: 1px solid #eee;">${activity.date}</td>
                <td style="padding: 10px 12px; border-bottom: 1px solid #eee; text-transform: capitalize;">${activity.type}</td>
                <td style="padding: 10px 12px; border-bottom: 1px solid #eee;">
                  <span style="display: inline-block; padding: 2px 8px; background: ${
                    activity.outcome === 'interested' ? '#dcfce7' : activity.outcome === 'invested' ? '#d1fae5' : activity.outcome === 'not_interested' ? '#fee2e2' : '#fef3c7'
                  }; color: ${
                    activity.outcome === 'interested' ? '#166534' : activity.outcome === 'invested' ? '#065f46' : activity.outcome === 'not_interested' ? '#991b1b' : '#92400e'
                  }; border-radius: 4px; font-size: 11px; font-weight: 500; text-transform: capitalize;">
                    ${activity.outcome.replace('_', ' ')}
                  </span>
                </td>
                <td style="padding: 10px 12px; border-bottom: 1px solid #eee; color: #666;">${activity.notes || '-'}</td>
              </tr>
            `
              )
              .join('')}
          </tbody>
        </table>
      </div>
      `
          : ''
      }

      <!-- Portfolio Holdings -->
      ${
        client.portfolio.length > 0
          ? `
      <div style="margin-bottom: 30px;">
        <h3 style="font-size: 18px; font-weight: 600; margin: 0 0 16px 0; color: #000;">💼 Current Portfolio</h3>
        <table style="width: 100%; border-collapse: collapse; font-size: 13px;">
          <thead>
            <tr style="background: #f5f5f5;">
              <th style="padding: 12px; text-align: left; border-bottom: 2px solid #ddd; font-weight: 600;">Investment</th>
              <th style="padding: 12px; text-align: left; border-bottom: 2px solid #ddd; font-weight: 600;">Type</th>
              <th style="padding: 12px; text-align: right; border-bottom: 2px solid #ddd; font-weight: 600;">Invested</th>
              <th style="padding: 12px; text-align: right; border-bottom: 2px solid #ddd; font-weight: 600;">Current</th>
              <th style="padding: 12px; text-align: right; border-bottom: 2px solid #ddd; font-weight: 600;">Performance</th>
            </tr>
          </thead>
          <tbody>
            ${client.portfolio
              .slice(0, 5)
              .map(
                (holding) => `
              <tr>
                <td style="padding: 10px 12px; border-bottom: 1px solid #eee; font-weight: 500;">${holding.investment_name}</td>
                <td style="padding: 10px 12px; border-bottom: 1px solid #eee; text-transform: capitalize;">${holding.investment_type.replace('_', ' ')}</td>
                <td style="padding: 10px 12px; border-bottom: 1px solid #eee; text-align: right;">${formatCurrency(holding.amount_invested)}</td>
                <td style="padding: 10px 12px; border-bottom: 1px solid #eee; text-align: right;">${formatCurrency(holding.current_value)}</td>
                <td style="padding: 10px 12px; border-bottom: 1px solid #eee; text-align: right; color: ${holding.performance >= 0 ? '#16a34a' : '#dc2626'}; font-weight: 600;">
                  ${holding.performance >= 0 ? '+' : ''}${holding.performance}%
                </td>
              </tr>
            `
              )
              .join('')}
          </tbody>
        </table>
      </div>
      `
          : ''
      }

      <!-- Footer -->
      <div style="border-top: 2px solid #e0e0e0; padding-top: 20px; margin-top: 40px;">
        <div style="display: flex; justify-content: space-between; align-items: center;">
          <div>
            <p style="margin: 0; font-size: 14px; font-weight: 600; color: #000;">${advisor.name}</p>
            <p style="margin: 4px 0 0 0; font-size: 12px; color: #666;">${advisor.company}</p>
            <p style="margin: 4px 0 0 0; font-size: 12px; color: #666;">${advisor.email} | ${advisor.phone}</p>
          </div>
          <div style="text-align: right;">
            <p style="margin: 0; font-size: 20px; font-weight: 700; color: #000;">AlphaForce</p>
            <p style="margin: 4px 0 0 0; font-size: 11px; color: #888;">Sales Intelligence & Advisor Copilot</p>
          </div>
        </div>
      </div>
    </div>
  `;
}

export async function generateClientPDF(
  client: ClientPDFData,
  predictions: PredictionData[] = [],
  advisor: AdvisorInfo = defaultAdvisor
): Promise<void> {
  const content = generatePDFContent(client, predictions, advisor);

  // Create a temporary container
  const container = document.createElement('div');
  container.innerHTML = content;
  container.style.position = 'absolute';
  container.style.left = '-9999px';
  container.style.top = '0';
  document.body.appendChild(container);

  const element = container.querySelector('#pdf-content') as HTMLElement | null;
  if (!element) {
    document.body.removeChild(container);
    throw new Error('PDF content not found');
  }

  const filename = `${client.name.replace(/\s+/g, '_')}_Summary_${new Date().toISOString().split('T')[0]}.pdf`;

  const opt = {
    margin: 10,
    filename,
    image: { type: 'jpeg' as const, quality: 0.98 },
    html2canvas: { scale: 2, useCORS: true },
    jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' as const },
  };

  try {
    await html2pdf().set(opt).from(element).save();
  } finally {
    document.body.removeChild(container);
  }
}
